package core

import (
	"encoding/json"
)

// StoryblokSdk Go SDK: generated schemas. Do not edit.
//
// Generated from the model: `main.kit.optspec` and each feature's
// `config.options` for OPTSPEC; entity `fields{}.type` for ENTITYSPEC.

const optspecJSON = "{\"allow\":{\"method\":\"GET,PUT,POST,PATCH,DELETE,OPTIONS\",\"op\":\"create,update,load,list,remove,command,direct,graphql\"},\"apikey\":\"\",\"auth\":{\"basic\":false,\"in\":\"\",\"name\":\"\",\"prefix\":\"\"},\"base\":\"http://localhost:8000\",\"clean\":{\"active\":true,\"hint\":\"0\",\"keys\":\"key,secret,token,password,passwd,authorization,cookie,credential,signature\",\"mask\":\"[redacted]\",\"min\":\"4\",\"values\":\"\"},\"entity\":{\"`$CHILD`\":{\"`$OPEN`\":true,\"active\":false,\"alias\":{}}},\"extend\":\"`$ANY`\",\"headers\":{\"`$CHILD`\":\"`$STRING`\"},\"prefix\":\"\",\"secret\":\"\",\"server\":{\"`$CHILD`\":\"\"},\"suffix\":\"\",\"system\":{\"fetch\":\"`$ANY`\"},\"test\":{\"active\":false,\"entity\":{\"`$OPEN`\":true}},\"utility\":{},\"feature\":{\"`$CHILD`\":{\"`$OPEN`\":true,\"active\":false},\"test\":[\"`$ONE`\",{\"`$OPEN`\":true,\"active\":[\"`$ONE`\",\"`$BOOLEAN`\",\"`$NIL`\"],\"entity\":[\"`$ONE`\",\"`$MAP`\",\"`$NIL`\"],\"net\":[\"`$ONE`\",\"`$MAP`\",\"`$NIL`\"]},\"`$NIL`\"]}}"

const entityspecJSON = "{}"

// Parsed ONCE, at package init. The spec is read on every client
// construction and never mutated, so a per-call parse would be pure waste —
// and a shared map is safe here for the same reason the spec is a constant:
// MakeOptions validates AGAINST it and writes into the options, never into
// the spec.
var (
	OPTSPEC    = mustSpec(optspecJSON)
	ENTITYSPEC = mustSpec(entityspecJSON)
)

func mustSpec(src string) map[string]any {
	var out map[string]any
	if err := json.Unmarshal([]byte(src), &out); err != nil {
		// Unreachable: generated by json.Marshal's counterpart and never
		// edited by hand. Panic rather than hand back an empty spec, which
		// would validate everything and fail far from the cause.
		panic("StoryblokSdk: embedded schema is not valid JSON: " + err.Error())
	}
	return out
}
